baseurl:          /

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jparyani's blog
tagline:          ''
description:      "A blog for describing programming projects that I've worked on.<br /><br /><a href=\"https://github.com/jparyani\" target=\"_blank\">@jparyani</a>"
url:              http://blog.jparyani.com
paginate:         5

author:
  name:           'Jason Paryani'
  url:            https://github.com/jparyani

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jparyani/jparyani.github.io
